-d /home/chandler/SSD2/repositories/msx-goauld-merge/fpga/impl/gwsynthesis/project.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst /home/chandler/SSD2/repositories/msx-goauld-merge/fpga/tang9k.cst
-cfg /home/chandler/SSD2/repositories/msx-goauld-merge/fpga/impl/pnr/device.cfg
-sdc /home/chandler/SSD2/repositories/msx-goauld-merge/fpga/Z80_goauld.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
